version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: alexsimons/fun-fair-node-dev:9.2.0
    entrypoint:
      - npm
      - run
      - compile
    volumes:
      - .:/app

#runs the node install