version: "3"
services:
  node-install:
    build:
      dockerfile: Dockerfile-install
      context: .
    image: alexsimons/nodeinstall:9.2.0
    volumes:
      - "./:/app"
    entrypoint:
      - /bin/bash
    command:
      - "-c"
      - "npm install"

#runs the node install